CREATE TABLE `LatestActivites`(
	`CreatedBy` VARCHAR(32),
	`CreatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	`ID` VARCHAR(10) NOT NULL,
	`LastUpdatedBy` VARCHAR(32),
	`LastUpdatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
	`PublishDate` VARCHAR(50) NOT NULL,
	`SoftDeleteFlag` BOOLEAN,
	`Summary` VARCHAR(250) NOT NULL,
	`URL` VARCHAR(100) NOT NULL,
	PRIMARY KEY(`ID`)
);
ALTER TABLE `LatestActivites`
	ADD CONSTRAINT `0558de1f0979c71008f86b886f0aa8` UNIQUE KEY(`ID`);
