CREATE TABLE `Modules`(
	`CourseID` VARCHAR(10) NOT NULL,
	`CreatedBy` VARCHAR(32),
	`CreatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	`LastUpdatedBy` VARCHAR(32),
	`LastUpdatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
	`ModuleID` BIGINT NOT NULL AUTO_INCREMENT,
	`ModuleName` VARCHAR(100) NOT NULL,
	`SoftDeleteFlag` BOOLEAN,
	PRIMARY KEY(`ModuleID`)
);
ALTER TABLE `Modules`
	ADD CONSTRAINT `2fb3c01d887b4204510566d9a168bc` UNIQUE KEY(`ModuleID`);
