CREATE TABLE `Users`(
	`CreatedBy` VARCHAR(32),
	`CreatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	`Email` VARCHAR(20) NOT NULL,
	`LastUpdatedBy` VARCHAR(32),
	`LastUpdatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
	`Name` VARCHAR(50) NOT NULL,
	`SoftDeleteFlag` BOOLEAN,
	PRIMARY KEY(`Email`)
);
ALTER TABLE `Users`
	ADD CONSTRAINT `3dffa6a80052a68ddebd53090a6da9` UNIQUE KEY(`Email`);
