CREATE TABLE `Courses`(
	`CourseID` VARCHAR(10) NOT NULL,
	`CreatedBy` VARCHAR(32),
	`CreatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	`LastUpdatedBy` VARCHAR(32),
	`LastUpdatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
	`SoftDeleteFlag` BOOLEAN,
	PRIMARY KEY(`CourseID`)
);
ALTER TABLE `Courses`
	ADD CONSTRAINT `fcbffcee0b1ab492663f9eaea486f4` UNIQUE KEY(`CourseID`);
